version: "3.7"
services:
  fastapi-app:
    container_name: fastapi-app
    build:
      context: .
    command: uvicorn main:app --host 0.0.0.0 --port 8000
    init: true
    ports:
      - 8000:8000
    volumes:
      - .:/app
    depends_on:
      - postgres_db
    environment: &app-environment
      DATABASE_URL: "postgresql+psycopg2://postgres:postgres@postgres_db:5432/postgres"
      GOOGLE_SERVICE_ACCOUNT_KEY_JSON: ${GOOGLE_SERVICE_ACCOUNT_KEY_JSON}

  email-forwarder:
    container_name: email-forwarder
    build:
      context: .
    command: python email_forwarder.py
    init: true
    volumes:
      - .:/app
    depends_on:
      - postgres_db
    restart: unless-stopped
    environment: *app-environment

  postgres_db:
    container_name: postgres_db
    image: postgres:latest
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
      POSTGRES_DB: postgres
    volumes:
      - ./pgdata:/var/lib/postgresql/data

volumes:
  pgdata:
    external: true

networks:
  default:
    name: email-forwarder
    external: true
  